OBJS +=                                 \
    passes/pift/pift.o                  \
    passes/pift/tsink.o                 \
    passes/pift/thook.o                 \
    passes/pift/tsum.o                  \
    passes/pift/ctrlreg.o               \
    passes/pift/keep_chisel_signal.o    \
    passes/pift/anno_chisel_sram.o
